
name: Release 

on:
  push:

env:
  #env_1 : dummy

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: ビルドa
        run: echo buildtesst
        run: zip -r pixsquare.zip . --exclude ".*"

      - name: リリースを作成する
        uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: tag_${{ github.ref }}_${{github.sha}}
          release_name: Release ${{ github.ref }}
          body: release body

 
      - name: リリースアセットをアップロードする
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          #upload_url: https://uploads.github.com/repos/data2coordi/pixsquare/releases/153632651/assets{?name,label}
          #upload_url:https://github.com/data2coordi/pixsquare/releases/download/latest/index3.php.zip
          asset_name: pixsquare.zip
          asset_path: ./pixsquare.zip
          asset_content_type: application/zip
