
name: Release 

on:
  push:

env:
  env_1 : aaabbb

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      # - name: ビルドa
        # run: echo build
          # ビルド処理を記述
      - run: echo "tag_name=${{ github.event.release.tag_name }}"
      - run: echo "release_name=${{ github.event.release.tag_name }}"

      - name: リリースを作成する
        uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}/v1
          release_name: Release ${{ github.ref }}
          body: releasee body

 
      - name: リリースアセットをアップロードする
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          #upload_url: https://uploads.github.com/repos/data2coordi/pixsquare/releases/153632651/assets{?name,label}
          #upload_url:https://github.com/data2coordi/pixsquare/releases/download/latest/index3.php.zip
          asset_name: pixsquare.zip
          asset_path: ./style.css
          asset_content_type: application/zip
