
name: Release 

on:
  push:

env:
  env_1 : aaabbb

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: ビルド
        # run: echo build
          # ビルド処理を記述
      - run: echo "tag_name=${{ github.event.release.tag_name }}"
      - run: echo "release_name=${{ github.event.release.tag_name }}"

      #- name: リリースを作成する
      #  uses: actions/create-release@v1
      #  id: create-release
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: tag6_${{ github.ref }}
      #    release_name: Release ${{ github.ref }}
      #    body: releasee body


      - name: リリースアセットをアップロードする
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #upload_url: ${{ steps.create-release.outputs.upload_url }}
          upload_url: https://uploads.github.com/repos/data2coordi/pixsquare/releases/153632651/assets{?name,label}https://uploads.github.com/repos/data2coordi/pixsquare/releases/153632651/assets{?name,label}
          asset_name: index3.php.zip
          asset_path: ./index.php
          asset_content_type: application/zip
