
name: Release 

on:
  push:

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: ビルド
        # run: echo build
          # ビルド処理を記述

      - name: リリースを作成する
        uses: actions/create-release@v1
        id: create-release
        with:
          tag_name: test_tag_name
          release_name: test_release_name
          body: test_body

      - name: リリースアセットをアップロードする
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          name: ${{ env.FILE_NAME }}
          path: ${{ env.FILE_PATH }}
