name: Hello World  # このworkflowの名前

on: # onで実行タイミングを設定
  [push] # 手動で実行するAction

jobs: # jobsで実行する内容を書く
  say_hello: # 実行する内容(job)の名前
    runs-on: ubuntu-latest # 実行するOS
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello World!" # 実行するコマンド
      - run: pwd
      - run: ls -l
      - run: echo test actions  > text.txt
      - run: git push 
